# A list of collections in the format
# [id]
# name = "collection name"
# description = "collection description"
# parameters_file = "name of file containing parameters for the collection _without_ the file extension"
#
# acctional_parameters is an _optional_ array of files containing additional parameters. If no array is specified, the default `dataset_parameters` file will be used. If the array contains one or more filenames (without the .toml extension), then the parameters in those files will be added to the default dataset_parameters. Parameters with the same name will override each other in the order that they're loaded, so if a file in the array contains a new version of the `row` parameter, the final set of parameters will contain the new version and not the old one. The parameters in each file are added, so if there are e.g., four parameter files specified, then all the parameters from all four files will be added to the default parameters (although overridden parameters will only be present once).
#
# Note: This file adds additional parameters to all Sentinel collections and additional parameters to all Sentinel-2 collections as a demonstration of how adding additional parameters works.

[SENTINEL1_L1_SLC]
name = "Sentinel-1 Level-1 (SLC)"
description = "The Sentinel-1 Level-1 Single Look Complex (SLC) products consist of focused SAR data geo-referenced using orbit and attitude data from the satellite and provided in zero-Doppler slant-range geometry. The products include a single look in each dimension using the full TX signal bandwidth and consist of complex samples preserving the phase information."
additional_parameters = ["sentinel_base_parameters"]

[SENTINEL1_L1_GRD]
name = "Sentinel-1 Level-1 (GRD)"
description = "The Sentinel-1 Level-1 Ground Range Detected (GRD) products consist of focused SAR data that has been detected, multi-looked and projected to ground range using an Earth ellipsoid model. Phase information is lost. The resulting product has approximately square resolution pixels and square pixel spacing with reduced speckle at the cost of reduced geometric resolution."
additional_parameters = ["sentinel_base_parameters"]

[SENTINEL1_L2_OCN]
name = "Sentinel-1 Level-2 (OCN)"
description = "The Sentinel-1 Level-2 OCN products include components for Ocean Swell spectra (OSW) providing continuity with ERS and ASAR WV and two new components: Ocean Wind Fields (OWI) and Surface Radial Velocities (RVL). The OSW is a two-dimensional ocean surface swell spectrum and includes an estimate of the wind speed and direction per swell spectrum. The OWI is a ground range gridded estimate of the surface wind speed and direction at 10 m above the surface derived from internally generated Level-1 GRD images of SM, IW or EW modes. The RVL is a ground range gridded difference between the measured Level-2 Doppler grid and the Level-1 calculated geometrical Doppler."
additional_parameters = ["sentinel_base_parameters"]

[SENTINEL2_L1C]
name = "Sentinel-2 Level-1C"
description = "The Sentinel-2 Level-1C products are Top-of-atmosphere reflectances in cartographic geometry. These products are systematically generated and the data volume is 500MB for each 100x100 km²."
additional_parameters = ["sentinel_base_parameters", "sentinel-2_parameters"]

[SENTINEL2_L2A]
name = "Sentinel-2 Level-2A"
description = "The Sentinel-2 Level-2A products are Bottom-of-atmosphere reflectances in cartographic geometry (prototype product). These products are generated using Sentinel-2 Toolbox and the data volume is 600MB for each 100x100 km²."
additional_parameters = ["sentinel_base_parameters", "sentinel-2_parameters"]

[SENTINEL3_SRAL_L1_CAL]
name = "Sentinel-3 SRAL Level-1 Calibration"
description = "SENTINEL-3 is the first Earth Observation Altimetry mission to provide 100% SAR altimetry coverage where LRM is maintained as a back-up operating mode. This is a Level 1 Calibration product."
additional_parameters = ["sentinel_base_parameters"]

[SENTINEL3_SRAL_L1_SRA]
name = "Sentinel-3 SRAL Level-1 SRA"
description = "SENTINEL-3 is the first Earth Observation Altimetry mission to provide 100% SAR altimetry coverage where LRM is maintained as a back-up operating mode. This is a Level 1 SRA product."
additional_parameters = ["sentinel_base_parameters"]

[SENTINEL3_SRAL_L2_LAN]
name = "Sentinel-3 SRAL Level-2 Land"
description = "SENTINEL-3 is the first Earth Observation Altimetry mission to provide 100% SAR altimetry coverage where LRM is maintained as a back-up operating mode. This is a product of Level 2 processing and geographical coverage over land."
additional_parameters = ["sentinel_base_parameters"]

[SENTINEL3_SRAL_L2_WAT]
name = "Sentinel-3 SRAL Level-2 Water"
description = "SENTINEL-3 is the first Earth Observation Altimetry mission to provide 100% SAR altimetry coverage where LRM is maintained as a back-up operating mode. This is a product of Level 2 processing and geographical coverage over water."
additional_parameters = ["sentinel_base_parameters"]

[SENTINEL3_OLCI_L1_EFR]
name = "Sentinel-3 OLCI Level-1 Full Resolution"
description = "SENTINEL-3 OLCI Level-1 product provides radiances for each pixel in the instrument grid, each view and each OLCI channel, plus annotation data associated to OLCI pixels. The output of this product is during EO processing mode for Full Resolution."
additional_parameters = ["sentinel_base_parameters"]

[SENTINEL3_OLCI_L1_ERR]
name = "Sentinel-3 OLCI Level-1 Reduced Resolution"
description = "SENTINEL-3 OLCI Level-1 product provides radiances for each pixel in the instrument grid, each view and each OLCI channel, plus annotation data associated to OLCI pixels. The output of this product is during EO processing mode for Reduced Resolution."
additional_parameters = ["sentinel_base_parameters"]

[SENTINEL3_OLCI_L2_LFR]
name = "Sentinel-3 OLCI Level-2 Land Full Resolution"
description = "SENTINEL-3 OLCI level-2 land product provides land and atmospheric geophysical parameters computed for full Resolution."
additional_parameters = ["sentinel_base_parameters"]

[SENTINEL3_OLCI_L2_LRR]
name = "Sentinel-3 OLCI Level-2 Land Reduced Resolution"
description = "SENTINEL-3 OLCI level-2 land product provides land and atmospheric geophysical parameters computed for reduced Resolution."
additional_parameters = ["sentinel_base_parameters"]

[SENTINEL3_SLSTR_L1_RBT]
name = "Sentinel-3 SLSTR Level-1 Radiances and Brightness Temperatures"
description = "SENTINEL-3 SLSTR Level-1 product provides radiances and brightness temperatures for each pixel in a regular image grid, each view and each SLSTR channel, plus annotations data associated with SLSTR pixels."
additional_parameters = ["sentinel_base_parameters"]

[SENTINEL3_SLSTR_L2_LST]
name = "Sentinel-3 SLSTR Level-2 Land Surface Temperature"
description = "SENTINEL-3 SLSTR Level-2 LST product provides land surface parameters generated on the wide 1 km measurement grid."
additional_parameters = ["sentinel_base_parameters"]

[METOFFICE-GLO-SST-L4-NRT-OBS-SST-V2]
name = "Global Observed Sea Surface Temperature"
description = "Daily analysis of sea surface temperature (SST), based on measurements from several satellite and in situ SST datasets, for the global ocean and some lakes."

[METNO-GLO-SEAICE_CONC-NORTH-L4-NRT-OBS]
name = "Arctic Ocean Observed Sea Ice Concentration"
description = "Daily sea ice concentration at 10km resolution in polar stereographic and EASE grid projections covering the Northern Hemisphere."

[METNO-GLO-SEAICE_CONC-SOUTH-L4-NRT-OBS]
name = "Antarctic Ocean Observed Sea Ice Concentration"
description = "Daily sea ice concentration at 10km resolution in polar stereographic and EASE grid projections covering the Southern Hemisphere."

[ARCTIC_ANALYSIS_FORECAST_PHYS_002_001_A]
name = "Arctic Ocean Physics Analysis and Forecast"
description = "Daily Arctic Ocean physics analysis to provide 10 days of forecast of the 3D physical ocean, including temperature, salinity, sea ice concentration, sea ice thickness, sea ice velocity and sea ice type."

[SEALEVEL_GLO_PHY_L4_NRT_OBSERVATIONS_008_046]
name = "Global Ocean Gridded L4 Sea Surface Heights and Derived Variables NRT"
description = "Daily products processed by the DUACS multimission altimeter data processing system. The geostrophic currents are derived from sla (geostrophic velocities anomalies, ugosa and vgosa variables) and from adt (absolute geostrophic velicities, ugos and vgos variables"

[GLOBAL_ANALYSIS_FORECAST_PHY_001_024]
name = "Global Ocean Physics Analysis and Forecast (Hourly)"
description = "Daily global ocean analysis and forecast system at 1/12 degree providing 10 days of 3D global ocean forecasts. These datasets include hourly mean surface fields for sea level height, temperature and currents (eastward sea water velocity, northward sea water velocity."

[MULTIOBS_GLO_PHY_NRT_015_003]
name = "Global Total Surface and 15m Current (Hourly)"
description = "This product is a 6 hourly NRT L4 global total velocity field at 0m and 15m. It consists of the zonal and meridional velocity at a 6h frequency and at 1/4 degree regular grid produced on a daily basis. These total velocity fields are obtained by combining CMEMS NRT satellite Geostrophic Surface Currents and modelled Ekman current at the surface and 15m depth (using ECMWF NRT wind)."

[METOP_A_GOME2_O3]
name = "MetOP-A GOME-2 Ozone (O3)"
description = "Daily global concentrations of atmospheric ozone. These data are crucial for monitoring atmospheric pollutants to keep a check on the health of the Earth's atmosphere."

[METOP_A_GOME2_NO2]
name = "MetOP-A GOME-2 Nitrogen Dioxide (NO2)"
description = "Daily global concentrations of atmospheric nitrogen dioxide. These data are crucial for monitoring atmospheric pollutants to keep a check on the health of the Earth's atmosphere."

[METOP_A_GOME2_TropNO2]
name = "MetOP-A GOME-2 Tropospheric Nitrogen Dioxide (NO2)"
description = "Daily global concentrations of tropospheric nitrogen dioxide. These data are crucial for monitoring atmospheric pollutants to keep a check on the health of the Earth's atmosphere."

[METOP_A_GOME2_SO2]
name = "MetOP-A GOME-2 Sulphur Dioxide (SO2)"
description = "Daily global concentrations of atmospheric sulphur dioxide. These data are crucial for monitoring atmospheric pollutants to keep a check on the health of the Earth's atmosphere."

[METOP_A_GOME2_SO2mass]
name = "MetOP-A GOME-2 Sulphur Dioxide (SO2) mass"
description = "Daily global concentrations of atmospheric sulphur dioxide mass. These data are crucial for monitoring atmospheric pollutants to keep a check on the health of the Earth's atmosphere."


[PROBAV_L2A_333M_V001]
name = "Proba-V Level-2A (333M)"
description = ""


[PROBAV_S1-TOC_1KM_V001]
name = "Proba-V S1-TOC (1KM)"
description = "Synthesis products with Top of Canopy (TOC) reflectances composited over defined time frame of 1 day for 1Km of spatial resolution."


[PROBAV_S1-TOA_1KM_V001]
name = "Proba-V S1-TOA (1KM)"
description = "Synthesis products with Top of Atmosphere (TOA) reflectances composited over defined time frame of 1 day for 1Km of spatial resolution."


[PROBAV_S10-TOC_1KM_V001]
name = "Proba-V S10-TOC (1KM)"
description = "Synthesis products with Top of Canopy (TOC) reflectances composited over defined time frame of 10 days for 1Km of spatial resolution."


[PROBAV_S10-TOC-NDVI_1KM_V001]
name = "Proba-V S10-TOC NDVI (1KM)"
description = "Synthesis products with Top of Canopy (TOC) reflectances composited over defined time frame of 10 days for 1Km of spatial resolution, containing only Normalized Difference Vegetation Index (NDVI)."


[PROBAV_L2A_1KM_V001]
name = "Proba-V Level-2A (1KM)"
description = "PROBA-V Level2A - 1KM segments contain the Level 1C (P product) data projected on a uniform 1Km grid."


[PROBAV_P_V001]
name = "Proba-V Level-1C"
description = "Raw data which is geo-located and radiometrically calibrated to Top Of Atmosphere (TOA) reflectance values."


[PROBAV_S1-TOC_333M_V001]
name = "Proba-V S1-TOC (333M)"
description = "Synthesis products with Top of Canopy (TOC) reflectances composited over defined time frame of 1 day for 333m of spatial resolution."


[PROBAV_S1-TOA_333M_V001]
name = "Proba-V S1-TOA (333M)"
description = "Synthesis products with Top of Atmosphere (TOA) reflectances composited over defined time frame of 1 day for 333m of spatial resolution."


[PROBAV_S10-TOC_333M_V001]
name = "PROBAV_S10-TOC_333M_V001"
description = "Synthesis products with Top of Canopy (TOC) reflectances composited over defined time frame of 10 days for 333m of spatial resolution."


[PROBAV_S10-TOC-NDVI_333M_V001]
name = "Proba-V S10-TOC NDVI (333M)"
description = "Synthesis products with Top of Canopy (TOC) reflectances composited over defined time frame of 10 days for 333m of spatial resolution, containing only Normalized Difference Vegetation Index (NDVI)."


[PROBAV_S1-TOC_100M_V001]
name = "Proba-V S1-TOC (100M)"
description = "Synthesis products with Top of Canopy (TOC) reflectances composited over defined time frame of 1 day for 100m of spatial resolution."


[PROBAV_S1-TOA_100M_V001]
name = "Proba-V S1-TOA (100M)"
description = "Synthesis products with Top of Atmosphere (TOA) reflectances composited over defined time frame of 1 day for 100m of spatial resolution."


[PROBAV_S1-TOC-NDVI_100M_V001]
name = "Proba-V S1-TOC NDVI (100M)"
description = "Synthesis products with Top of Atmosphere (TOA) reflectances composited over defined time frame of 1 day for 100m of spatial resolution containing only Normalized Difference Vegetation Index (NDVI)"


[PROBAV_S5-TOC_100M_V001]
name = "Proba-V S5-TOC (100M)"
description = "Synthesis products with Top of Canopy (TOC) reflectances composited over defined time frame of 5 days for 100m of spatial resolution."


[PROBAV_S5-TOA_100M_V001]
name = "Proba-V S5-TOA (100M)"
description = "Synthesis products with Top of Atmosphere (TOA) reflectances composited over defined time frame of 5 days for 100m of spatial resolution."


[PROBAV_S5-TOC-NDVI_100M_V001]
name = "Proba-V S5-TOC NDVI (100M)"
description = "Synthesis products with Top of Atmosphere (TOA) reflectances composited over defined time frame of 5 days for 100m of spatial resolution."


[PROBAV_L2A_100M_V001]
name = "Proba-V Level-2A (100M)"
description = "PROBA-V Level2A - 100M segments contain the Level 1C (P product) data projected on a uniform 100m grid."


# Plan4All collections
[OPEN_LAND_USE_MAP]
name = "Open Land Use Map"
description = "The main idea is to put Open Land Use dataset and also its metadata (from micka.lesprojekt.cz) in RDF format into Virtuoso and explore SPARQL queries that would combine data with metadata. For instance: Show me the datasets (municipalities) where more than 50% of the area is covered by residential areas and data were collected not later than 5 years ago? This query combines some metadata (such as year of data collection and municipality which data covers) with data itself (object features with residential land use). For automatization of such queries it is necessary to have both data and metadata available for querying and interconnected. In ideal case the output will be endpoint where it will be possible to query both OLU data and metadata, some model queries and possibly some visualization of query results."


# GLASS LAI collections
[LAI_1KM_AVHRR_8DAYS_GL]
name = "GLASS Leaf Area Index AVHRR 8 days"
description = "The GLASS Leaf Area Index (LAI) product, a global LAI product with long time series, generated from AVHRR reflectance, and released by the Center for Global Change Data Processing and Analysis of Beijing Normal University. The GLASS LAI product has a temporal resolution of 8 days and is available from 1982 to 2015."


[LAI_1KM_MODIS_8DAYS_GL]
name = "GLASS Leaf Area Index MODIS 8 days"
description = "The GLASS Leaf Area Index (LAI) product, a global LAI product with long time series, derived from MODIS land surface reflectance (MOD09A1), and released by the Center for Global Change Data Processing and Analysis of Beijing Normal University. The GLASS LAI product has a temporal resolution of 8 days and is available from 1982 to 2015."


# Static EBV collections
[TREE_SPECIES_DISTRIBUTION_HABITAT_SUITABILITY]
name = "Tree Species Distribution Habitat Suitability"
description = "European Distribution of the specie Fagus sylvatica for the years 2020, 2050 and 2080, based on different models such as ENS, CCCMA, CSIRO, HADCM3 (Habitat Suitability future)."


[FLOOD_HAZARD_EU_GL]
name = "Flood Hazard Europe/Global"
description = "The map depicts flood prone areas in Europe for flood events with 10-year return period. Cell values indicate water depth (in m). The map can be used to assess flood exposure and risk of population and assets. NOTE: this dataset is based on JRC elaborations and is not an official flood hazard map."


[RSP_AVHRR_1KM_ANNUAL_USA]
name = "AVHRR Remote Sensing Phenology"
description = "The Remote Sensing Phenology (RSP) collection is a set of nine annual phenological metrics for the conterminous United States. Researchers at the U.S. Geological Survey (USGS) Earth Resources Observation and Science (EROS) Center utilize data gathered by satellite sensors to track seasonal changes in vegetation. These datasets are provided by the sensor Advanced Very High Resolution Radiometer (AVHRR) from National Oceanic and Atmospheric Administration (NOAA) polar-orbiting satellites."


[EMODIS_PHENOLOGY_250M_ANNUAL_USA]
name = "eMODIS Remote Sensing Phenology"
description = "The Remote Sensing Phenology (RSP) collection is a set of nine annual phenological metrics for the conterminous United States. Researchers at the U.S. Geological Survey (USGS) Earth Resources Observation and Science (EROS) Center utilize data gathered by satellite sensors to track seasonal changes in vegetation. These datasets are provided by the sensor Moderate Resolution Imaging Spectroradiometer (MODIS) carried aboard National Aeronautics and Space Administration (NASA) Terra and Aqua satellites."