# A list of XML namespaces in the format alias = "uri"

opensearch = "http://a9.com/-/spec/opensearch/1.1/"
atom = "http://www.w3.org/2005/Atom"
param = "http://a9.com/-/opensearch/extensions/param/1.0/"
custom = "http://example.com/opensearchextensions/1.0/"
geo = "http://a9.com/-/opensearch/extensions/geo/1.0/"
time = "http://a9.com/-/opensearch/extensions/time/1.0/"
dc = "http://purl.org/dc/elements/1.1/"
georss = "http://www.georss.org/georss"
gml = "http://www.opengis.net/gml/3.2"
eop = "http://www.opengis.net/eop/2.1"
om = "http://www.opengis.net/om/2.0"
esipdiscovery = "http://commons.esipfed.org/ns/discovery/1.2/"
eo = "http://a9.com/-/opensearch/extensions/eo/1.0/"
sar = "http://www.opengis.net/sar/2.1"