# Additional parameters for Sentinel-1 GRD collections

[swath]
title = "acquisition mode"
os_name = "Swath"
namespace = "custom"
minimum = 0
maximum = 1

[orbit_direction]
title = "Orbit direction"
os_name = "OrbitDirection"
namespace = "custom"
minimum = 0
maximum = 1

[polarisation]
title = "Polarisation"
os_name = "TransmitterReceiverPolarisation"
namespace = "custom"
minimum = 0
maximum = 1

[product_type]
title = "Product Type"
os_name = "ProductType"
namespace = "custom"
minimum = 0
maximum = 1