# Additional parameters for Sentinel-1 GRD collections

[swath]
title = "Swath identifier (e.g. Envisat ASAR has 7 distinct swaths (I1,I2,I3...I7) that correspond to precise incidence angles for the sensor). Value list can be retrieved with codeSpace"
os_name = "swathIdentifier"
namespace = "eo"
minimum = 0
maximum = 1

[orbit_direction]
title = "A string identifying the acquisition orbit direction. Possible values are: ASCENDING, DESCENDING"
os_name = "orbitDirection"
namespace = "eo"
minimum = 0
maximum = 1
  [[orbit_direction.options]]
  value = "ASCENDING"
  label = "ASCENDING acquisition orbit direction"
  [[orbit_direction.options]]
  value = "DESCENDING"
  label = "DESCENDING acquisition orbit direction"

[polarisation]
title = "A string identifying polarisation"
os_name = "TransmitterReceiverPolarisation"
namespace = "custom"
minimum = 0
maximum = 1

[product_type]
title = "A string identifying the ProductType (eg. GRD)"
os_name = "ProductType"
namespace = "custom"
minimum = 0
maximum = 1