# Additional parameters for Sentinel-1 GRD collections

[swath]
title = "Swath identifier (e.g. Envisat ASAR has 7 distinct swaths (I1,I2,I3...I7) that correspond to precise incidence angles for the sensor). Value list can be retrieved with codeSpace"
os_name = "swathIdentifier"
namespace = "eo"
minimum = 0
maximum = 1

[orbit_direction]
title = "Orbit direction"
os_name = "OrbitDirection"
namespace = "custom"
minimum = 0
maximum = 1

[polarisation]
title = "Polarisation"
os_name = "TransmitterReceiverPolarisation"
namespace = "custom"
minimum = 0
maximum = 1

[product_type]
title = "Product Type"
os_name = "ProductType"
namespace = "custom"
minimum = 0
maximum = 1